// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package endpointmonitoring

import (
	"github.com/vlnevyhosteny/go-monitor-service/database"
)

// Injectors from wire.go:

func Wire(databaseFile string) *Service {
	db := database.ProvideConnection(databaseFile)
	endpointMonitoringSQLRepository := ProvideRepository(db)
	endpointmonitoringService := ProvideService(endpointMonitoringSQLRepository)
	return endpointmonitoringService
}
